/**
 * RSS Feed Generator for Cloudflare Workers
 * Supports HTML embedding and custom feed configurations
 */

import { RSSFeedBuilder } from './rss-builder';
import { FeedConfig, FeedItem } from './types';

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    // Handle different routes
    if (url.pathname === '/rss' || url.pathname === '/feed') {
      return generateRSSFeed();
    }

    if (url.pathname === '/') {
      return new Response(getHTMLPage(), {
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      });
    }

    return new Response('Not Found', { status: 404 });
  },
};

/**
 * Generate an RSS feed with example content
 */
function generateRSSFeed(): Response {
  // Example feed configuration
  const feedConfig: FeedConfig = {
    title: 'My RSS Feed',
    description: 'A simple RSS feed generated by Cloudflare Workers',
    link: 'https://example.com',
    language: 'en-us',
    copyright: `Copyright ${new Date().getFullYear()}`,
    lastBuildDate: new Date(),
  };

  // Example feed items with HTML content
  const feedItems: FeedItem[] = [
    {
      title: 'First Post with HTML',
      link: 'https://example.com/posts/first-post',
      description: `
        <h2>Welcome to our RSS feed!</h2>
        <p>This is an example post with <strong>HTML content</strong> embedded directly in the feed.</p>
        <ul>
          <li>HTML tags are properly escaped</li>
          <li>Images and links work great</li>
          <li>Code blocks are supported</li>
        </ul>
        <img src="https://via.placeholder.com/600x400" alt="Example image" />
      `,
      pubDate: new Date('2025-01-15'),
      author: 'admin@example.com (Admin)',
      guid: 'https://example.com/posts/first-post',
    },
    {
      title: 'Second Post with Rich Content',
      link: 'https://example.com/posts/second-post',
      description: `
        <div style="font-family: Arial, sans-serif;">
          <h2>Rich HTML Content</h2>
          <p>This post demonstrates rich HTML content in RSS feeds:</p>
          <blockquote style="border-left: 4px solid #ccc; padding-left: 16px; margin: 16px 0;">
            "RSS feeds can contain full HTML content, making them perfect for blogs and news sites."
          </blockquote>
          <p>Here's a code example:</p>
          <pre style="background: #f4f4f4; padding: 12px; border-radius: 4px;"><code>const rss = new RSSFeedBuilder(config);</code></pre>
        </div>
      `,
      pubDate: new Date('2025-01-20'),
      author: 'admin@example.com (Admin)',
      guid: 'https://example.com/posts/second-post',
      category: 'Technology',
    },
    {
      title: 'Third Post - Latest Update',
      link: 'https://example.com/posts/third-post',
      description: `
        <article>
          <h2>Latest Updates</h2>
          <p>Check out our latest features and improvements!</p>
          <h3>What's New:</h3>
          <ol>
            <li><strong>HTML Embedding</strong> - Full HTML support in feed items</li>
            <li><strong>Custom Styling</strong> - Inline CSS for better presentation</li>
            <li><strong>Media Support</strong> - Images, videos, and audio</li>
          </ol>
          <p>Read more on our <a href="https://example.com/blog">blog</a>!</p>
        </article>
      `,
      pubDate: new Date('2025-01-25'),
      author: 'admin@example.com (Admin)',
      guid: 'https://example.com/posts/third-post',
      category: 'Updates',
    },
  ];

  // Build the RSS feed
  const rssBuilder = new RSSFeedBuilder(feedConfig);
  const rssXML = rssBuilder.addItems(feedItems).build();

  return new Response(rssXML, {
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}

/**
 * Generate HTML landing page with feed information
 */
function getHTMLPage(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RSS Feed Generator</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 {
      color: #f38020;
      border-bottom: 3px solid #f38020;
      padding-bottom: 10px;
    }
    .feed-link {
      background: #f4f4f4;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
    }
    .feed-link a {
      color: #f38020;
      text-decoration: none;
      font-weight: bold;
      font-size: 18px;
    }
    .feed-link a:hover {
      text-decoration: underline;
    }
    .features {
      margin: 30px 0;
    }
    .features li {
      margin: 10px 0;
    }
    code {
      background: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
    }
  </style>
</head>
<body>
  <h1>RSS Feed Generator for Cloudflare Workers</h1>

  <p>Welcome! This is a simple RSS feed generator running on Cloudflare Workers with full HTML embedding support.</p>

  <div class="feed-link">
    <p>Subscribe to our RSS feed:</p>
    <a href="/rss">/rss</a> or <a href="/feed">/feed</a>
  </div>

  <div class="features">
    <h2>Features</h2>
    <ul>
      <li><strong>Full HTML Support</strong> - Embed rich HTML content in your feed items</li>
      <li><strong>CDATA Encoding</strong> - Proper encoding for HTML content in RSS</li>
      <li><strong>Standard RSS 2.0</strong> - Compatible with all RSS readers</li>
      <li><strong>Easy Customization</strong> - Simple API for creating custom feeds</li>
      <li><strong>Fast & Scalable</strong> - Powered by Cloudflare Workers</li>
    </ul>
  </div>

  <div class="features">
    <h2>How to Use</h2>
    <ol>
      <li>Modify the feed configuration in <code>src/index.ts</code></li>
      <li>Add your feed items with HTML content</li>
      <li>Deploy to Cloudflare Workers</li>
      <li>Share your feed URL with readers</li>
    </ol>
  </div>

  <footer style="margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;">
    <p>Built with Cloudflare Workers | <a href="https://github.com" style="color: #f38020;">View on GitHub</a></p>
  </footer>
</body>
</html>`;
}
